### PR TITLE
Using connected function when unify 

### PR DESCRIPTION
**Pull request by KhaledSamir**
check whether or not if two elements are in the same set using the connected function in unionfind.java.

### CODE REVIEW

**Comment by williamfiset** [comment]
This isn't really adding anything new so I'm going to close

**Comment by KhaledSamir** [comment]
Thanks, William for your comment. If we are not using connected function? why then we have in the first place?

**Comment by williamfiset** [comment]
connected is public, so anyone can use it! Just because it isn't being used internally doesn't mean it's not useful. The connected method just wraps having to find which two components two nodes are part of. 

```java
UnionFind uf = new UnionFind(5);
uf.unify(0, 3);
if (uf.connected(0, 3)) {
  // do something awesome
}
```

**Comment by KhaledSamir** [comment]
Sure, I agree with you, of course it's useful that's why I tried to use it in the unify function. I still think the change is adding an easier way to understand the unify function, anyways, I also see your point.

**Comment by williamfiset** [comment]
It does annoy me slightly that the find method is called 4 times to unify two elements. Twice in the connected method and then twice in the unify method. There's path compression, so the second accesses should be O(1) anyways

**Pull request merged**
