### PR TITLE
Update UnionFind.java

### PR DESCRIPTION
**Pull request by berkelmas**
Make component size 0 if it is merged because that node has already been merged to another so the size should be 0 at the end.

### CODE REVIEW

**Comment by williamfiset** [comment]
Sure...? In practice this shouldn't really matter because you don't ever need to lookup the size of previous components.

**Comment by berkelmas** [comment]
True but just wanted to have the data structure clean even if not used. Thanks for merging 👍

**Comment by abhinavos7a** [comment]
@berkelmas @williamfiset Shouldn't it be 

`sz[root2] = 0;` instead of `id[root2] = 0;` 

and for the else part

`sz[root1] = 0;` instead of `id[root1] = 0;`

**Comment by berkelmas** [comment]
@abhinavos7a True. That should be it. Opening up a new PR for that. Thanks for catching that up 👍 CC: @williamfiset

**Comment by berkelmas** [comment]
Now opened up a new PR for this fix:
https://github.com/williamfiset/Algorithms/compare/master...berkelmas:patch-2

**Pull request merged**
