### PR TITLE
Added quick select.

### PR DESCRIPTION
**Pull request by jasonsaruulo**
I do not know whether this was still in progress or already merged (did not find anything in master branch about quick select).
#6

### CODE REVIEW

**Review by williamfiset — APPROVED** [review]
Thank you, looks good!

**Comment by williamfiset** [comment]
The format presubmit is failing, you just need to run `gradle goJF` to run the Google Java formatter and then you can submit

**Comment by williamfiset** [comment]
nvm, I just merged it ran the formatter in 735a57a870eb716c38ac10669f1ca15c8f782fdb

**Comment by jasonsaruulo** [comment]
Oh, cool, thanks! Next time I will make sure to run it beforehand! Sorry for the extra effort. :)

**Pull request merged**
